name: dart_simple
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  spyglass:
    path: ../../packages/spyglass

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
